
---
- name: Create Binaries directory
  become: yes
  become_user: root
  file: path={{ tmp_dir }} state=directory mode=0755

- name: Create Logs directory
  become: yes
  become_user: root
  file: path={{ logs_dir }} state=directory mode=0755

- name: Copy binaries file
  become: yes
  become_user: root
  copy:
    src: "{{ tmp_dir }}/{{ bin_file }}"
    dest: "{{ tmp_dir }}"
    owner: root
    group: root
    mode: '0644'

# For online download of IIM, use this tasks
#- name: Download IBM Installation Manager
#  get_url:
#    url: "{{ iim_repository_url }}/{{ bin_file }}"
#    dest: "{{ tmp_dir }}/{{ bin_file }}"
#    mode: 0755
#    checksum: sha256:{{ bin_file_sha256 }}

- name: Extract IBM Installation Manager
  become: yes
  become_user: root
  unarchive:
    src: "{{ tmp_dir }}/{{ bin_file }}"
    dest: "{{ tmp_dir }}/"
    remote_src: yes

- name: Install/Update IBM Installation Manager
  become: yes
  become_user: root
  command:
    chdir={{ tmp_dir }}
    {{ tmp_dir }}/tools/imcl install com.ibm.cic.agent -acceptLicense -installationDirectory {{ iim_install_location }} -repositories {{ tmp_dir }} -log {{ logs_dir }}/iim_install.{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.log
  register: cout
  changed_when: (cout.stdout.find('Installed com.ibm.cic.agent') != -1) or (cout.stdout.find('Updated to com.ibm.cic.agent') != -1) 


